// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPosts = `-- name: CreatePosts :one
INSERT INTO posts (id, url,title,description,published_at,created_at, updated_at,feed_id)
VALUES ($1, $2, $3, $4, $5,$6,$7,$8)
RETURNING id, url, title, description, published_at, created_at, updated_at, feed_id
`

type CreatePostsParams struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Description sql.NullString
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPosts,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT posts.id, url, title, description, published_at, posts.created_at, posts.updated_at, posts.feed_id, feed_follows.id, feed_follows.created_at, feed_follows.updated_at, user_id, feed_follows.feed_id FROM posts JOIN feed_follows ON posts.feed_id = feed_follows.feed_id 
WHERE feed_follows.feed_id=$1
`

type GetPostsRow struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Description sql.NullString
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FeedID      uuid.UUID
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	UserID      uuid.UUID
	FeedID_2    uuid.UUID
}

func (q *Queries) GetPosts(ctx context.Context, feedID uuid.UUID) ([]GetPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.UserID,
			&i.FeedID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
